#!/bin/sh

# Common commands {{{
alias rm="rm -vI" # I don't trust myself anymore
alias mv="mv -iv"
alias cp="cp -iv"
alias ls='ls --color=always --group-directories-first'
alias grep='grep --color=auto'
alias c='clear'
alias la='ls -lah'
alias l='ls -lh'
alias dc='docker-compose'
alias untar="tar -cvzf"
alias notes='cd ~/Notes/ && nvim .'
alias dot='cd ~/dotfiles'
alias own='sudo chown $USER:$USER'
alias ownR='sudo chown -R $USER:$USER'
alias root='sudo -E zsh'
#alias code='vscodium --enable-features=UseOzonePlatform --ozone-platform=wayland'
alias code='vscodium'
alias ivm='vim'
alias vmi='vim'
alias :q='exit'
alias SS='sudo systemctl'
alias neofetch='fastfetch'
alias kubectl='minikube kubectl --' 
# }}}

# Utils {{{
source ~/r2
alias r2='aws s3 --endpoint-url $R2_ENDPOINT'
# }}}

# Git {{{
alias g='lazygit'
alias ga='git add'
alias gp='git push'
alias gpl='git pull'
alias gl='git log'
alias gs='git status'
alias gd='git diff'
alias gm='git commit -m'
alias gb='git branch'
alias gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gcl='git clone'
# }}}
