#!/bin/sh

# Common commands
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias c='clear'
alias la='ls -lah'
alias l='ls -lh'
alias dc='docker-compose'
alias untar="tar -cvzf $1"
alias notes='cd ~/Notes/'
alias rdunst='killall dunst && notify-send config reloaded'
alias dot='cd ~/dotfiles'
alias own='sudo chown $USER:$USER'
alias ownR='sudo chown -R $USER:$USER'
alias root='sudo -E zsh'

# Utils
alias gtc='~/Scripts/utils/gtc.sh'
alias fixP='sudo ~/Scripts/utils/fixPermissions.sh'
source ~/r2
alias r2='aws s3 --endpoint-url $R2_ENDPOINT'

# Git
alias g='git'
alias ga='git add'
alias gp='git push'
alias gpl='git pull'
alias gl='git log'
alias gs='git status'
alias gd='git diff'
alias gm='git commit -m'
alias gb='git branch'
alias gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gcl='git clone'
