# Window rules

windowrule {
	name = picture-in-picture
	float = on
	match:title = (Picture in picture)
}

windowrule {
	name = rofi
	match:class = ^(Rofi)$
	float = on
}
windowrule {
	name = reminder 
	match:title = (Reminder)
	float = on
}

windowrule {
	name = pavucontrol
	match:class = ^(org.pulseaudio.pavucontrol)$
	float = on
}
windowrule {
	name = xdg-desktop-portal-gtk
	match:class = ^(xdg-desktop-portal-gtk)$
	float = on
}


# Xwayland Window rules for screensharing

windowrule {
	name = xwaylandvideobridge
	match:class = ^(xwaylandvideobridge)$
	opacity = 0.0 override
	max_size = 1 1
	no_anim = on
	no_initial_focus = true
	no_blur = on
}
# windowrule = noanim,class:^(xwaylandvideobridge)$
# windowrule = noinitialfocus,class:^(xwaylandvideobridge)$
# windowrule = maxsize 1 1,class:^(xwaylandvideobridge)$
# windowrule = noblur,class:^(xwaylandvideobridge)$
